// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQv8mdWX0n7347xxMtQjVaPNyTTxIVnRk',
    appId: '1:872023771713:web:6d2a3fd15c9b9af47314c0',
    messagingSenderId: '872023771713',
    projectId: 'skincareappforbetul',
    authDomain: 'skincareappforbetul.firebaseapp.com',
    storageBucket: 'skincareappforbetul.firebasestorage.app',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Q9rYsOP7uwQ_OQAaA1PcBHJ56ZYBDhw',
    appId: '1:872023771713:android:f5bae19443535b487314c0',
    messagingSenderId: '872023771713',
    projectId: 'skincareappforbetul',
    storageBucket: 'skincareappforbetul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOxagemzAi43BxeMKjn6uLeBStLTXFpQ',
    appId: '1:872023771713:ios:6707ecf817d771ff7314c0',
    messagingSenderId: '872023771713',
    projectId: 'skincareappforbetul',
    storageBucket: 'skincareappforbetul.firebasestorage.app',
    iosBundleId: 'com.lucielle.skinCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOxagemzAi43BxeMKjn6uLeBStLTXFpQ',
    appId: '1:872023771713:ios:6707ecf817d771ff7314c0',
    messagingSenderId: '872023771713',
    projectId: 'skincareappforbetul',
    storageBucket: 'skincareappforbetul.firebasestorage.app',
    iosBundleId: 'com.lucielle.skinCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQv8mdWX0n7347xxMtQjVaPNyTTxIVnRk',
    appId: '1:872023771713:web:7ab217cff04c69677314c0',
    messagingSenderId: '872023771713',
    projectId: 'skincareappforbetul',
    authDomain: 'skincareappforbetul.firebaseapp.com',
    storageBucket: 'skincareappforbetul.firebasestorage.app',
  );
}
